# Generated by Django 6.1 on 2026-08-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailing_owner_message_owner_recipient_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=20),
        ),
    ]
